"""
bist_attach_capture.py — lldb Python helpers for attach-to-PID trace.

This module is imported into lldb via ``command script import``.
It provides ``capture_state`` which can be registered as a breakpoint
callback.

Usage from lldb (generated by bist_trace.py):
    (lldb) command script import /path/to/bist_attach_capture.py
    (lldb) breakpoint set --address 0x12345678
    (lldb) breakpoint command add -s python 1 -o "bist_attach_capture.capture_state"
    (lldb) continue
    (lldb) detach
"""
from __future__ import annotations

import sysdef capture_state(frame, bp_loc, internal_dict):
    """Breakpoint callback: print register state for _bist_ function."""
    import lldb

    thread = frame.thread
    target = thread.process.target

    print()
    print("=" * 72)
    print(f"  BIST TRACE: at 0x{frame.pc:x}")
    print(f"  BP name: {bp_loc.GetBreakpoint().GetName() or '(unnamed)'}")
    print("=" * 72)

    # Caller info
    if thread.num_frames > 1:
        f1 = thread.frames[1]
        print(f"  Caller:   {f1.name or ''}  addr=0x{f1.pc:x}")
    if thread.num_frames > 2:
        f2 = thread.frames[2]
        print(f"  Frame 2:  {f2.name or ''}  addr=0x{f2.pc:x}")

    print()
    print("  ── Argument registers (x0-x7) ──")
    for rn in ["x0", "x1", "x2", "x3", "x4", "x5", "x6", "x7"]:
        reg = frame.FindRegister(rn)
        if reg and reg.IsValid():
            v = reg.GetValue()
            try:
                as_i = int(v, 16)
                tag = ""
                if as_i > 0x100000000:
                    tag = " [PTR]"
                elif 0x20 <= as_i <= 0x7e:
                    tag = f" '{chr(as_i)}'"
                print(f"    {rn:>4s} = {v:>20s}  ({as_i:>12d}){tag}")
            except (ValueError, TypeError):
                print(f"    {rn:>4s} = {v}")

    print()
    print("  ── Float registers (d0-d7) ──")
    for rn in [f"d{i}" for i in range(8)]:
        reg = frame.FindRegister(rn)
        if reg and reg.IsValid():
            print(f"    {rn:>4s} = {reg.GetValue()}")

    # Other key registers
    print()
    print("  ── Other registers ──")
    for rn in ["fp", "lr", "sp", "x8", "x9", "x10", "x28"]:
        reg = frame.FindRegister(rn)
        if reg and reg.IsValid():
            print(f"    {rn:>4s} = {reg.GetValue()}")

    # Stack (first 16 words)
    sp_reg = frame.FindRegister("sp")
    if sp_reg and sp_reg.IsValid():
        try:
            sp = int(sp_reg.GetValue(), 16)
            error = lldb.SBError()
            mem = thread.process.ReadMemory(sp, 128, error)
            if error.Success() and mem:
                print()
                print("  ── Stack at SP (first 16 words) ──")
                for i in range(0, len(mem), 8):
                    w = int.from_bytes(mem[i : i + 8], "little")
                    addr = sp + i
                    tag = ""
                    if w > 0x100000000:
                        tag = " [PTR]"
                    elif 0x20 <= w <= 0x7e:
                        tag = f" '{chr(w)}'"
                    print(f"    SP+0x{i:03x} = 0x{w:016x}  (addr 0x{addr:x}){tag}")
        except Exception:
            pass

    # Read Stata internal stack pointer
    for i in range(target.GetNumModules()):
        mod = target.GetModuleAtIndex(i)
        fn = mod.file.basename if mod.file else ""
        if "libstata" in fn.lower():
            for s in mod.sections:
                if s.name == "__TEXT":
                    base = s.GetLoadAddress(target)
                    stata_sp_addr = base + 0x39b7000 + 0x108
                    try:
                        error = lldb.SBError()
                        mem = thread.process.ReadMemory(stata_sp_addr, 8, error)
                        if error.Success() and mem:
                            stata_sp = int.from_bytes(mem, "little")
                            print(f"\n  Stata internal stack ptr: 0x{stata_sp:x}")
                            # Read tsmat at stack SP
                            if stata_sp:
                                tsmat_mem = thread.process.ReadMemory(stata_sp, 8, error)
                                if error.Success() and tsmat_mem:
                                    tsmat = int.from_bytes(tsmat_mem, "little")
                                    print(f"  *SP (tsmat): 0x{tsmat:x}")
                                    if tsmat:
                                        data_mem = thread.process.ReadMemory(tsmat, 8, error)
                                        if error.Success() and data_mem:
                                            data_ptr = int.from_bytes(data_mem, "little")
                                            print(f"  tsmat[0] data: 0x{data_ptr:x}")
                                            if data_ptr:
                                                import struct
                                                val_mem = thread.process.ReadMemory(data_ptr, 8, error)
                                                if error.Success() and val_mem:
                                                    val = struct.unpack("<d", val_mem)[0]
                                                    print(f"  *(double*)data = {val}")
                    except Exception:
                        pass
                    break
            break

    print("=" * 72)
    print()

    return False  # auto-continue


def __lldb_init_module(debugger, internal_dict):
    print("[bist_attach_capture] Loaded.", file=sys.stderr)
