name: Build & Test

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
