name: Test Matrix

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        run: echo "py=${{ matrix.python-version }}"
